# Build with:
# docker build --no-cache -t "alex88ridolfi/pulsar-miner-2.0-prestozl:latest" - < Dockerfile_pulsar-miner-prestozl-ubuntu22.04-cuda11.8-ampere-sm86.txt

FROM nvidia/cuda:11.8.0-devel-ubuntu22.04


MAINTAINER Alessandro Ridolfi "alex88 . ridolfi AT gmail DOT com"

# Suppress debconf warnings
ENV DEBIAN_FRONTEND noninteractive
ENV PSRHOME /software

RUN apt-get update &&\
    apt-get install -y --no-install-recommends \
    git \   
    ca-certificates

RUN apt-get install -y python3-pip nano emacs less latex2html rsync

# Make Python 3.10 the default version
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
RUN update-alternatives --install /usr/bin/python  python  /usr/bin/python3.10 1

RUN python3 -m pip install numpy==1.23.5

#######################
# PULSAR_MINER
#######################

WORKDIR ${PSRHOME}
RUN git clone -b PrestoZL https://github.com/alex88ridolfi/PULSAR_MINER.git
ENV PATH="${PSRHOME}/PULSAR_MINER:${PATH}"



#######################
# TEMPO
#######################
RUN apt-get install -y  autoconf gsl-bin libgsl-dev tcsh gfortran libtool

WORKDIR $PSRHOME
RUN git clone https://git.code.sf.net/p/tempo/tempo

ENV TEMPO=$PSRHOME"/tempo" \
    PATH=$PATH:$PSRHOME"/tempo/bin"

WORKDIR $PSRHOME/tempo
RUN ./prepare

RUN ./configure --prefix=$PSRHOME/tempo && \
    make && \
    make install

RUN python3 -m pip install numpy



#######################
# PRESTO_ZL
#######################
WORKDIR $PSRHOME
RUN apt-get install -y libfftw3-bin libfftw3-dev libglib2.0-dev libcfitsio-bin libcfitsio-dev pgplot5 libx11-dev libpng-dev

RUN git clone https://github.com/alex88ridolfi/PrestoZL.git

ENV PGPLOT_DIR="/usr/lib/pgplot5" \
    PGPLOT_FONT="/usr/lib/pgplot5/grfont.dat" \
    PGPLOT_INCLUDES="/usr/include" \
    PGPLOT_BACKGROUND="white" \
    PGPLOT_FOREGROUND="black" \
    PGPLOT_DEV="/xs"

ENV PRESTO="/software/PrestoZL"
ENV PRESTO2_ON_GPU="/software/PrestoZL"
ENV PATH="${PRESTO}/bin:${PATH}"
ENV LD_LIBRARY_PATH="${PRESTO}/lib:${LD_LIBRARY_PATH}"

WORKDIR ${PRESTO}/src

RUN make makewisdom && \
    make prep && \
    make 

ENV PATH=${PATH}

#######################
# PRESTO
#######################
WORKDIR $PSRHOME


RUN git clone https://github.com/scottransom/presto.git

WORKDIR $PSRHOME/presto
RUN git checkout 82fff054a0da017127149211dd577959a3f54c9e

ENV PRESTO="/software/presto"
ENV PATH="${PRESTO}/bin:${PATH}"
ENV LD_LIBRARY_PATH="${PRESTO}/lib:${LD_LIBRARY_PATH}"

WORKDIR ${PRESTO}/src

RUN make makewisdom && \
    make prep && \
    make


WORKDIR $PRESTO

RUN python3 -m pip install .


######################
# PSRALEX
#######################
WORKDIR $PSRHOME

RUN git clone https://github.com/alex88ridolfi/PSRALEX.git PSRALEX

ENV PSRALEX=$PSRHOME/PSRALEX
ENV PATH=$PATH:$PSRALEX


RUN echo 'export PS1="\[\e[4;30m\]\u@\h\[\e[0m\]:\[\e[1;10m\]\w\[\e[0m\]\$ (docker)> "' >> ~/.bashrc
RUN echo 'alias ls="ls --color=auto"'       >> ~/.bashrc
RUN echo 'alias ll="ls -l"'                 >> ~/.bashrc
RUN echo 'alias LL="ls -lL"'                >> ~/.bashrc
RUN echo 'alias lt="ls -lrt --color"'       >> ~/.bashrc
RUN echo 'alias lh="ls -lh --color"'        >> ~/.bashrc
RUN echo 'alias rm="rm -i"'                 >> ~/.bashrc
RUN echo 'alias cp="cp -i"'                 >> ~/.bashrc
RUN echo 'alias mv="mv -i"'                 >> ~/.bashrc
RUN echo 'alias emacs="emacs -nw"'          >> ~/.bashrc
RUN echo 'alias presto_gpu="export PRESTO=/software/PrestoZL && export LD_LIBRARY_PATH=${PRESTO}/lib:${LD_LIBRARY_PATH} && export PATH=${PRESTO}/bin:${PATH}"'          >> ~/.bashrc



RUN ldconfig /usr/local/lib

WORKDIR ${PSRHOME}


